<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>TavernLib</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="MelonLoader" />
    <Reference Include="Root.Township" />
    <Reference Include="0Harmony" />
    <Reference Include="Alta.Api.DataTransferModels" />
    <Reference Include="Alta.Api.Client" />
    <Reference Include="Alta.NetworkTransport.Runtime" />
    <Reference Include="Alta.Serialization.Runtime" />
    <Reference Include="Alta.Platform" />
    <Reference Include="System.IdentityModel.Tokens.Jwt" />
    <Reference Include="System.Core" />
    <Reference Include="UnityEngine.CoreModule" />
    <Reference Include="NLog" />
    <Reference Include="System.Xml" />
    <Reference Include="Alta.IO" />
    <Reference Include="System.Net.Http" />
    <Reference Include="Newtonsoft.Json" />
    <Reference Include="MonoMod.RuntimeDetour" />
    <Reference Include="Alta.CommandLine" />
    <Reference Include="System.IO.Compression.FileSystem" />
    <Reference Include="UnityEngine.IMGUIModule" />
    <Reference Include="Alta.Global.Runtime" />
    <Reference Include="Alta.Values" />
  </ItemGroup>
</Project>